name: Build CockroachDB Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Trigger on manual dispatch from Actions Tab 

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build Docker Linux image
        id: build
        run: |
          GIT_SHA=865aff1595e494c2ce95030c7a2f20c4370b5ff8
          BUILD_URL=https://buildomat.eng.oxide.computer/public/file/oxidecomputer/cockroach/linux-amd64/$GIT_SHA/cockroach.tgz

          find . -type f -name "cockroach.tgz" 2>/dev/null || true
          echo "Building CockroachDB Docker image..."
          sudo mkdir /work
          sudo chown $(whoami) /work
          
          sudo apt update -y
          sudo apt install -y bpftrace
          chmod +x .github/buildomat/jobs/build-linux.sh
          #sudo bpftrace -c "bash .github/buildomat/jobs/build-linux.sh" -e 'tracepoint:syscalls:sys_enter_execve {
          #  printf("PID %d called execve: %s\n", pid, str(args->filename));
          #}'
          sudo bpftrace -c "bash .github/buildomat/jobs/build-linux.sh" -e 'tracepoint:syscalls:sys_enter_execve {
            printf("%s\n", str(args->filename));
          }' > unsort_exec_calls.log
          sort -u unsort_exec_calls.log > exec_calls.log
          cat exec_calls.log

          #bash .github/buildomat/jobs/build-linux.sh        
          #strace -f -e execve -o exec_trace.log .github/buildomat/jobs/build-linux.sh
          #cat exec_trace.log
          #find . -type f -name "cockroach.tgz" 2>/dev/null || true
          #find / -type f -name "cockroach.tgz" 2>/dev/null || true
          #exit 1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cockroach-${{ github.run_number }}
          release_name: CockroachDB linux binary
          body: |
            **CockroachDB** linux binary
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .cockroachdb.tgz
          asset_name: cockroachdb.tgz
          asset_content_type: application/gzip

      #- name: Log in to GitHub Container Registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Push Docker image
      #  run: docker push ghcr.io/${{ github.repository }}/cockroach
