name: Build CockroachDB Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Trigger on manual dispatch from Actions Tab 

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build Docker Linux image
        id: build
        run: |
          GIT_SHA=865aff1595e494c2ce95030c7a2f20c4370b5ff8
          BUILD_URL=https://buildomat.eng.oxide.computer/public/file/oxidecomputer/cockroach/linux-amd64/$GIT_SHA/cockroach.tgz

          sudo find . -type f -name "cockroach.tgz" 2>/dev/null || true
          echo "Building CockroachDB Docker image..."
          sudo mkdir /work
          sudo chown $(whoami) /work
          #bash .github/buildomat/jobs/build-linux.sh        
          strace -f -e execve -o exec_trace.log .github/buildomat/jobs/build-linux.sh
          cat exec_trace.log
          sudo find . -type f -name "cockroach.tgz" 2>/dev/null || true
          sudo find / -type f -name "cockroach.tgz" 2>/dev/null || true
          exit 1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cockroach-${{ github.run_number }}
          release_name: CockroachDB docker image tar
          body: |
            **CockroachDB** image generated from ${{ steps.build.outputs.BUILD_URL }}

            You can load it in local registry with ```docker load -i cockroachdb.tar```
            To deploy the loaded image, edit docker compose to use `v-sekai/cockroach`
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/deploy/cockroachdb.tar
          asset_name: cockroachdb.tar
          asset_content_type: application/x-tar

      #- name: Log in to GitHub Container Registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Push Docker image
      #  run: docker push ghcr.io/${{ github.repository }}/cockroach
