name: Cross-Platform Build

on:
  push
   # branches:
      #- main

jobs:
  build-cross-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Linux binary
        run: |
          GIT_SHA=865aff1595e494c2ce95030c7a2f20c4370b5ff8
          sudo apt update -y
          sudo apt install -y tree
          echo "Building CockroachDB for Linux"
          curl -sS -O https://buildomat.eng.oxide.computer/public/file/oxidecomputer/cockroach/linux-amd64/$GIT_SHA/cockroach.tgz
          tar -xvzf cockroach.tgz
          tree -a cockroach

          cp ./cockroach/cockroach build/deploy/cockroach
          cp ./cockroach/lib/* build/deploy/
          cp -r licenses build/deploy/

          cd build/deploy
          docker buildx build \
                --output type=docker,dest=./cockroachdb.tar \
                --platform linux/amd64 \
                --progress plain \
                --tag "v-sekai/cockroach" .
          
